# Generated by Django 3.2 on 2024-02-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=5)),
                ('ename', models.CharField(max_length=150)),
                ('eage', models.IntegerField(default=20)),
                ('esal', models.IntegerField()),
                ('edesg', models.CharField(choices=[('0', '-- Select Designation --'), ('1', 'Intern'), ('2', 'Junior Trainee'), ('3', 'Junior Developer'), ('4', 'Other')], default='0', max_length=10)),
            ],
        ),
    ]
